package com.internshiphub.opportunity;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.sql.DriverManager;

import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

class OpportunityMigrationTest {
    @Test
    void keepsLegacyUrlsInTheirStageSpecificFields() throws Exception {
        try (EmbeddedPostgres postgres = EmbeddedPostgres.start()) {
            String jdbcUrl = postgres.getJdbcUrl("postgres", "postgres");
            try (var connection = DriverManager.getConnection(jdbcUrl);
                 var statement = connection.createStatement()) {
                statement.execute("""
                        CREATE TABLE opportunities (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            title VARCHAR(255) NOT NULL,
                            company VARCHAR(255) NOT NULL,
                            posting_url VARCHAR(2048) NOT NULL UNIQUE,
                            stage VARCHAR(255) NOT NULL)
                        """);
                statement.execute("""
                        INSERT INTO opportunities (title, company, posting_url, stage) VALUES
                            ('Saved Intern', 'Example Co', 'https://example.com/apply', 'SAVED'),
                            ('Applied Intern', 'Other Co', 'https://example.com/status', 'APPLIED')
                        """);
            }

            Flyway.configure().dataSource(jdbcUrl, "postgres", "postgres")
                    .locations("classpath:db/migration")
                    .baselineOnMigrate(true).baselineVersion("1").load().migrate();

            try (var connection = DriverManager.getConnection(jdbcUrl);
                 var statement = connection.createStatement();
                 var rows = statement.executeQuery("SELECT stage, discovery_url, application_url, status_url FROM opportunities ORDER BY id")) {
                rows.next();
                assertEquals("SAVED", rows.getString("stage"));
                assertEquals("https://example.com/apply", rows.getString("application_url"));
                assertEquals(null, rows.getString("status_url"));
                rows.next();
                assertEquals("APPLIED", rows.getString("stage"));
                assertEquals("https://example.com/status", rows.getString("status_url"));
                assertEquals(null, rows.getString("application_url"));
            }
        }
    }
}
